name: 🧪 Postman API Tests - ServeRest

on:
  push:
    branches: [testes]
  pull_request:
    branches: [testes]

jobs:
  run-newman-tests:
    runs-on: ubuntu-24.04 # <- CORRIGIDO

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      - name: 1 - API DE USUARIOS
        run: |
          newman run "1_API_USUARIOS.postman_collection.json" \
            -e "ServeRest Env.postman_environment.json" \
            --reporters cli,html \
            --reporter-html-export newman-report.html

      - name: 2 - API DE LOGIN
        run: |
          newman run "2_API_LOGIN.postman_collection.json" \
            -e "ServeRest Env.postman_environment.json" \
            --reporters cli,html \
            --reporter-html-export newman-report.html

      - name: 3 - API DE PRODUTOS
        run: |
          newman run "3_API_PRODUTOS.postman_collection.json" \
            -e "ServeRest Env.postman_environment.json" \
            --reporters cli,html \
            --reporter-html-export newman-report.html

      - name: 4 - API DE CARRINHO
        run: |
          newman run "4_API_Carrinho.postman_collection.json" \
            -e "ServeRest Env.postman_environment.json" \
            --reporters cli,html \
            --reporter-html-export newman-report.html

      - name: 📤 Publicar relatório do Newman
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.html
